"""Pulling leads generated by paid ad platforms straight into the CRM's
leads table as new "New"-stage clients, instead of retyping what came in
through a Facebook/Instagram lead form or a TikTok Instant Form export.

Two paths, because the two platforms need different amounts of typing:

  Facebook & Instagram — read through Windsor.ai's `facebook_leads`
  connector. marketing.py already holds the Windsor.ai API key (set once
  under Settings > Marketing) and the tiny HTTP client that talks to it;
  this module reuses both rather than asking for a second key. One click
  on Leads > Import from ads pulls in whatever was submitted in the chosen
  window. Instagram lead ads run through the same Meta infrastructure and
  the same connector, so both platforms come back in one pull — but
  Windsor.ai doesn't say which placement a given submission came from, so
  every lead from this connector is recorded with source "Facebook Ads".

  TikTok — Windsor.ai has no lead-form connector for TikTok (only ad-spend
  reporting), so this reads the CSV that TikTok Ads Manager's Leads Center
  lets you download by hand, matching whatever headers TikTok used (they
  vary with the questions asked on each Instant Form) against a list of
  aliases below.

Both paths land in the same place: leads.ad_lead_id carries a stable
"<platform>:<external id>" key, so importing the same window twice, or an
overlapping TikTok export, never creates the same client a second time —
see idx_leads_ad_lead_id in db.py. Zero new dependencies: csv and hashlib
are standard library, and the Facebook/Instagram side rides on marketing.py's
existing urllib client.
"""
import csv
import hashlib
import io
import re

import marketing
from db import execute, log, next_ref, now, query

# ---------------------------------------------------------------------------
# Facebook & Instagram, via Windsor.ai's facebook_leads connector
# ---------------------------------------------------------------------------

# Field IDs as exposed by Windsor.ai's facebook_leads connector — confirmed
# against the live connector (get_fields), not guessed. Windsor.ai needs a
# one-time OAuth authorization per Meta ad account before this connector has
# any data — see the "Import from ads" page, which links to that
# authorization when it's still missing. Note there is no field that says
# whether a submission came from a Facebook or an Instagram placement, so
# every lead from this connector is recorded with source "Facebook Ads".
FACEBOOK_FIELDS = [
    "id", "created_time", "full_name", "email", "phone_number",
    "form_name", "campaign", "adset_name", "ad_name",
]

# Re-use the same last-7/30/90-days choices as the ad-spend report, so the
# two "pick a window" controls in the CRM behave the same way.
RANGES = marketing.RANGES
range_dates = marketing.range_dates


def facebook_ready():
    """Whether the shared Windsor.ai key is in place. Doesn't confirm the
    facebook_leads connector itself has been authorized — Windsor.ai reports
    that as a normal fetch error, which import_facebook_leads() surfaces."""
    return marketing.api_key_present()


def _clean(value):
    if value is None:
        return None
    s = str(value).strip()
    return s or None


def fetch_facebook_leads(date_from, date_to):
    """(ok, rows_or_message) straight from Windsor.ai, unfiltered."""
    return marketing.fetch("facebook_leads", date_from, date_to,
                            fields=FACEBOOK_FIELDS)


def import_facebook_leads(date_from, date_to, user_id):
    """Fetch and insert. Returns a summary dict; never raises."""
    ok, rows = fetch_facebook_leads(date_from, date_to)
    if not ok:
        return {"ok": False, "error": rows}

    added = skipped = 0
    stamp = now()
    source = "Facebook Ads"
    for row in rows:
        ext_id = _clean(row.get("id"))
        if not ext_id:
            skipped += 1
            continue
        ad_lead_id = f"facebook:{ext_id}"
        if query("SELECT 1 FROM leads WHERE ad_lead_id = ?", (ad_lead_id,), one=True):
            skipped += 1
            continue

        name = _clean(row.get("full_name")) or "Facebook lead"
        notes = _context_note(
            form=row.get("form_name"), campaign=row.get("campaign"),
            adset=row.get("adset_name"), ad=row.get("ad_name"),
            submitted=row.get("created_time"))

        ref = next_ref("PRE-L", "leads")
        lid = execute(
            "INSERT INTO leads (ref, full_name, email, phone, source, status,"
            " notes, ad_lead_id, created_at, updated_at)"
            " VALUES (?,?,?,?,?,?,?,?,?,?)",
            (ref, name, _clean(row.get("email")), _clean(row.get("phone_number")),
             source, "New", notes, ad_lead_id, stamp, stamp))
        log(user_id, "Captured lead", "lead", lid,
            f"{ref} — {name} via {source} (imported from ads)")
        added += 1

    log(user_id, "Imported ad leads", detail=(
        f"Facebook/Instagram: {added} added, {skipped} skipped ({date_from} to {date_to})"))
    return {"ok": True, "added": added, "skipped": skipped, "fetched": len(rows)}


def _context_note(form=None, campaign=None, adset=None, ad=None, submitted=None):
    parts = []
    if form:
        parts.append(f"Form: {form}")
    if campaign:
        parts.append(f"Campaign: {campaign}")
    if adset:
        parts.append(f"Ad set: {adset}")
    if ad:
        parts.append(f"Ad: {ad}")
    if submitted:
        parts.append(f"Submitted: {submitted}")
    return " · ".join(parts) or None


# ---------------------------------------------------------------------------
# TikTok, via a CSV exported by hand from TikTok Ads Manager's Leads Center
# ---------------------------------------------------------------------------

# TikTok's export headers vary with the questions on each Instant Form, so
# columns are matched by alias rather than by a fixed position. Keys here are
# normalised (lower-cased, punctuation-stripped) forms of headers actually
# seen on TikTok exports.
TIKTOK_ALIASES = {
    "full_name": ["name", "full name", "your name", "lead name"],
    "email": ["email", "email address"],
    "phone": ["phone number", "phone", "mobile", "mobile number",
             "contact number", "whatsapp number"],
    "lead_id": ["lead id", "leadid", "submission id", "id"],
    "created_time": ["create time", "created time", "submission time", "time"],
    "form_name": ["form name", "instant form", "form"],
    "ad_name": ["ad name", "ad"],
    "campaign_name": ["campaign name", "campaign"],
}


def _normalise_header(h):
    return re.sub(r"[^a-z0-9]+", " ", (h or "").strip().lower()).strip()


def _map_headers(headers):
    """header (as it appears in the file) -> our field name, best match."""
    norm = {_normalise_header(h): h for h in headers}
    mapping = {}
    for field, aliases in TIKTOK_ALIASES.items():
        for alias in aliases:
            if alias in norm:
                mapping[field] = norm[alias]
                break
    return mapping


def preview_tiktok_csv(raw_bytes, limit=12):
    """Parse without writing anything. Returns (headers, mapping, rows,
    total_count) for a review screen, or raises ValueError with a message
    fit to show the person who uploaded the file."""
    text = raw_bytes.decode("utf-8-sig", errors="replace")
    reader = csv.DictReader(io.StringIO(text))
    if not reader.fieldnames:
        raise ValueError("That file has no columns the CRM could read.")
    mapping = _map_headers(reader.fieldnames)
    if "full_name" not in mapping and "phone" not in mapping and "email" not in mapping:
        raise ValueError(
            "None of the columns in that file look like a name, phone number "
            "or email. Check it's the Leads Center export and try again.")

    all_rows = list(reader)
    rows = []
    for i, raw in enumerate(all_rows):
        rows.append(_extract_tiktok_row(raw, mapping, i))
    return reader.fieldnames, mapping, rows[:limit], len(all_rows)


def _extract_tiktok_row(raw, mapping, index):
    get = lambda field: _clean(raw.get(mapping[field])) if field in mapping else None
    name = get("full_name")
    phone = get("phone")
    email = get("email")
    ext_id = get("lead_id")
    if not ext_id:
        # No id column in the export: derive a stable one from whatever
        # identifies this person, so re-importing the same file is still
        # safe even without TikTok's own id.
        basis = "|".join(filter(None, [phone, email, name, get("created_time")]))
        ext_id = "row" + hashlib.sha1(basis.encode("utf-8")).hexdigest()[:16] if basis else None
    return {
        "index": index, "full_name": name, "phone": phone, "email": email,
        "ext_id": ext_id, "notes": _context_note(
            form=get("form_name"), campaign=get("campaign_name"), ad=get("ad_name")),
        "usable": bool(name or phone or email) and bool(ext_id),
    }


def import_tiktok_csv(raw_bytes, user_id):
    """Parse and insert in one pass. Returns a summary dict; raises
    ValueError (same message as preview_tiktok_csv) if the file is unusable."""
    text = raw_bytes.decode("utf-8-sig", errors="replace")
    reader = csv.DictReader(io.StringIO(text))
    if not reader.fieldnames:
        raise ValueError("That file has no columns the CRM could read.")
    mapping = _map_headers(reader.fieldnames)
    if "full_name" not in mapping and "phone" not in mapping and "email" not in mapping:
        raise ValueError(
            "None of the columns in that file look like a name, phone number "
            "or email. Check it's the Leads Center export and try again.")

    added = skipped = 0
    stamp = now()
    for i, raw in enumerate(reader):
        item = _extract_tiktok_row(raw, mapping, i)
        if not item["usable"]:
            skipped += 1
            continue
        ad_lead_id = f"tiktok:{item['ext_id']}"
        if query("SELECT 1 FROM leads WHERE ad_lead_id = ?", (ad_lead_id,), one=True):
            skipped += 1
            continue
        name = item["full_name"] or "TikTok lead"
        ref = next_ref("PRE-L", "leads")
        lid = execute(
            "INSERT INTO leads (ref, full_name, email, phone, source, status,"
            " notes, ad_lead_id, created_at, updated_at)"
            " VALUES (?,?,?,?,?,?,?,?,?,?)",
            (ref, name, item["email"], item["phone"], "TikTok Ads", "New",
             item["notes"], ad_lead_id, stamp, stamp))
        log(user_id, "Captured lead", "lead", lid,
            f"{ref} — {name} via TikTok Ads (imported from CSV)")
        added += 1

    log(user_id, "Imported ad leads",
        detail=f"TikTok: {added} added, {skipped} skipped")
    return {"ok": True, "added": added, "skipped": skipped}
